[versions]
agp = "8.4.2"
kotlin = "1.9.22"
coreKtx = "1.13.1"
observableSession = "1.0.0"
coroutinesGftx = "1.0.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
coroutines = "1.7.3"
jetbrainsKotlinJvm = "1.9.22"
mavenPublishVersion = "0.30.0"
koinVersion = "3.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
gft-observablesession = { module = "com.gft.mobile:observable-session", version.ref = "observableSession" }
gft-coroutines = { module = "com.gft.mobile:coroutines", version.ref = "coroutinesGftx" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishVersion" }

